### ISSUE TITLE
Add support for ABP syntax rules.

### ISSUE THREAD

**Issue by riddlerboss248** [zenstorage/Reddit-NSFW-Unblur#1]
I have created an ABP syntax based on your uBlock Origin script. Here is the [repository](https://raw.githubusercontent.com/riddlerboss248/NSFW-unblur-Reddit/main/Remove-NSFW.txt). Maybe you could add it to the uBlock Origin filters for users using ABP syntax adblockers e.g. Vivaldi and brave. Since Vivaldi on Android and iOS cannot add custom rules, I would also propose having it as a file, since Vivaldi on android and iOS can only subscribe to url:s.

I have validated it on brave and Vivaldi on android, and it works as intended.

I just tried it for fun but since I know I won't have time to maintain the repo I thought it would be better to hand it over to you.

**Comment by zenstorage** [comment]
Sorry for the delay, I was traveling, nice, I can add the file with the filters with uBO and ABP syntax

**Comment by zenstorage** [comment]
I added a filter specifically for Brave since it supports uBO syntax but does not support ```remove-attr()``` and the ```remove-attr``` scriptlet can be used as a substitute
